version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
    environment:
      - DATABASE_URL=postgresql://fileprocessor:${DB_PASSWORD}@db:5432/fileprocessor
      - PYTHONPATH=/app
    volumes:
      - ollama_models:/root/.ollama  # Persist Ollama models
    depends_on:
      - db
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - app_network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=fileprocessor
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=fileprocessor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fileprocessor"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network
    ports:
      - "5432:5432"  # Only needed if you want to access DB from host

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:  # Persist PostgreSQL data
  ollama_models:  # Persist Ollama models
