version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "11434:11434"  # Ollama port
      - "8501:8501"    # Streamlit port
    volumes:
      - ./data/ollama:/root/.ollama
    environment:
      - OLLAMA_MODEL=llama3.2

volumes:
  ollama-data:
